-- AJEFA Quiz — statistiques simples dans la même interface
-- 1) Dans Supabase > SQL Editor, remplacez MON-CODE-ADMIN par votre code privé.
-- 2) Exécutez tout ce script une seule fois.

create extension if not exists pgcrypto;

create table if not exists public.quiz_events (
  id bigint generated by default as identity primary key,
  quiz_id text not null,
  session_id uuid not null,
  event_type text not null check (event_type in ('quiz_viewed','quiz_started','question_answered','quiz_completed','quiz_restarted')),
  question_number integer,
  correct boolean,
  score integer,
  total_questions integer,
  created_at timestamptz not null default now()
);

create index if not exists quiz_events_quiz_event_idx on public.quiz_events (quiz_id, event_type);
create index if not exists quiz_events_quiz_session_idx on public.quiz_events (quiz_id, session_id);

alter table public.quiz_events enable row level security;

drop policy if exists "quiz public insert only" on public.quiz_events;
create policy "quiz public insert only"
on public.quiz_events
for insert
to anon, authenticated
with check (
  char_length(quiz_id) between 1 and 80
  and event_type in ('quiz_viewed','quiz_started','question_answered','quiz_completed','quiz_restarted')
);

-- Le public ne reçoit aucune permission SELECT sur quiz_events.
revoke select, update, delete on public.quiz_events from anon, authenticated;
grant insert on public.quiz_events to anon, authenticated;

drop table if exists public.quiz_admin_config;
create table public.quiz_admin_config (
  key text primary key,
  value text not null
);

alter table public.quiz_admin_config enable row level security;
revoke all on public.quiz_admin_config from anon, authenticated;

insert into public.quiz_admin_config(key, value)
values ('admin_code_hash', crypt('MON-CODE-ADMIN', gen_salt('bf')))
on conflict (key) do update set value = excluded.value;

create or replace function public.get_quiz_stats(p_quiz_id text, p_admin_code text)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  expected_hash text;
  v_visits integer;
  v_started integer;
  v_completed integer;
  v_average_score numeric;
  v_total_questions integer;
  v_question_stats jsonb;
begin
  select value into expected_hash
  from public.quiz_admin_config
  where key = 'admin_code_hash';

  if expected_hash is null or crypt(p_admin_code, expected_hash) <> expected_hash then
    raise exception 'invalid_admin_code' using errcode = '28000';
  end if;

  select count(distinct session_id)::integer into v_visits
  from public.quiz_events where quiz_id = p_quiz_id and event_type = 'quiz_viewed';

  select count(distinct session_id)::integer into v_started
  from public.quiz_events where quiz_id = p_quiz_id and event_type = 'quiz_started';

  select count(distinct session_id)::integer into v_completed
  from public.quiz_events where quiz_id = p_quiz_id and event_type = 'quiz_completed';

  select coalesce(round(avg(score)::numeric, 1), 0), coalesce(max(total_questions), 5)
  into v_average_score, v_total_questions
  from public.quiz_events where quiz_id = p_quiz_id and event_type = 'quiz_completed';

  select coalesce(jsonb_agg(row_data order by question_number), '[]'::jsonb)
  into v_question_stats
  from (
    select
      question_number,
      count(*)::integer as answered,
      count(*) filter (where correct is true)::integer as correct,
      case when count(*) = 0 then 0 else round((100.0 * count(*) filter (where correct is true) / count(*))::numeric, 1) end as correct_rate
    from public.quiz_events
    where quiz_id = p_quiz_id and event_type = 'question_answered' and question_number is not null
    group by question_number
  ) row_data;

  return jsonb_build_object(
    'visits', coalesce(v_visits, 0),
    'started', coalesce(v_started, 0),
    'completed', coalesce(v_completed, 0),
    'completion_rate', case when coalesce(v_started,0) = 0 then 0 else round((100.0 * v_completed / v_started)::numeric, 1) end,
    'average_score', coalesce(v_average_score, 0),
    'total_questions', coalesce(v_total_questions, 5),
    'question_stats', v_question_stats
  );
end;
$$;

revoke all on function public.get_quiz_stats(text, text) from public;
grant execute on function public.get_quiz_stats(text, text) to anon, authenticated;
